
spring.application.name=plateforme-citoyenne-api

# Base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/participation_citoyenne
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Port de l'API
server.port=8082
